-- Drop existing tables if they exist to avoid conflicts
DROP TABLE IF EXISTS FactSales CASCADE;
DROP TABLE IF EXISTS DimDate CASCADE;
DROP TABLE IF EXISTS DimCustomer CASCADE;
DROP TABLE IF EXISTS DimProduct CASCADE;
DROP TABLE IF EXISTS DimEmployee CASCADE;
DROP TABLE IF EXISTS DimCategory CASCADE;
DROP TABLE IF EXISTS DimShipper CASCADE;
DROP TABLE IF EXISTS DimSupplier CASCADE;

DROP TABLE IF EXISTS staging_order_details CASCADE;
DROP TABLE IF EXISTS staging_orders CASCADE;
DROP TABLE IF EXISTS staging_products CASCADE;
DROP TABLE IF EXISTS staging_customers CASCADE;
DROP TABLE IF EXISTS staging_employees CASCADE;
DROP TABLE IF EXISTS staging_categories CASCADE;
DROP TABLE IF EXISTS staging_shippers CASCADE;
DROP TABLE IF EXISTS staging_suppliers CASCADE;